//! DB bindings — 数据库schema与模型声明
//!
//! 使用 Diesel table! 宏定义schema，derive宏生成查询/插入代码。
//! 数据库相关的所有声明集中在此，bindings外禁止SQL字面量。

use diesel::prelude::*;

// ---------------------------------------------------------------------------
// Schema — Diesel table! 宏定义
// ---------------------------------------------------------------------------

diesel::table! {
    messages (id) {
        id -> BigInt,
        sender -> Text,
        role -> Text,
        content -> Text,
        timestamp -> Text,
        read_status -> Text,
        msg_type -> Text,
        recipient -> Text,
    }
}

// ---------------------------------------------------------------------------
// Models — Queryable / Insertable structs
// ---------------------------------------------------------------------------

/// A complete message record (all columns, for SELECT queries).
#[derive(Debug, Clone, Queryable, Selectable)]
#[diesel(table_name = messages)]
pub struct MessageRow {
    pub id: i64,
    pub sender: String,
    pub role: String,
    pub content: String,
    pub timestamp: String,
    pub read_status: String,
    pub msg_type: String,
    pub recipient: String,
}

/// For inserting a new message (id is auto-generated by SQLite).
#[derive(Debug, Insertable)]
#[diesel(table_name = messages)]
pub struct NewMessage<'a> {
    pub sender: &'a str,
    pub role: &'a str,
    pub content: &'a str,
    pub timestamp: &'a str,
    pub read_status: &'a str,
    pub msg_type: &'a str,
    pub recipient: &'a str,
}

// ---------------------------------------------------------------------------
// Constants — role/status/type values
// ---------------------------------------------------------------------------

pub const ROLE_USER: &str = "user";
pub const ROLE_AGENT: &str = "agent";
pub const ROLE_SYSTEM: &str = "system";
pub const STATUS_READ: &str = "read";
pub const STATUS_UNREAD: &str = "unread";
pub const TYPE_CHAT: &str = "chat";

// ---------------------------------------------------------------------------
// Schema migration SQL (raw SQL, Diesel doesn't auto-migrate)
// ---------------------------------------------------------------------------

pub const CREATE_MESSAGES_TABLE: &str =
    "CREATE TABLE IF NOT EXISTS messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        sender TEXT NOT NULL DEFAULT '',
        role TEXT NOT NULL DEFAULT '',
        content TEXT NOT NULL DEFAULT '',
        timestamp TEXT NOT NULL DEFAULT '',
        read_status TEXT NOT NULL DEFAULT '',
        msg_type TEXT NOT NULL DEFAULT '',
        recipient TEXT NOT NULL DEFAULT ''
    )";

pub const CHECK_RECIPIENT_COLUMN: &str = "SELECT recipient FROM messages LIMIT 0";

pub const ADD_RECIPIENT_COLUMN: &str =
    "ALTER TABLE messages ADD COLUMN recipient TEXT NOT NULL DEFAULT ''";