//! DB bindings — 数据库schema与模型声明
//!
//! 使用 Diesel table! 宏定义schema，derive宏生成查询/插入代码。
//! 数据库相关的所有声明集中在此，bindings外禁止SQL字面量。

use diesel::prelude::*;
use mad_hatter::dao;

// ---------------------------------------------------------------------------
// Database pool declarations — dao! macro manages connection pools
// ---------------------------------------------------------------------------

dao!(ChatDb, "data/chat.db");
dao!(MemoryDb, "memory/memory.db");

// ---------------------------------------------------------------------------
// Schema — Diesel table! 宏定义
// ---------------------------------------------------------------------------

diesel::table! {
    messages (id) {
        id -> BigInt,
        sender -> Text,
        role -> Text,
        content -> Text,
        timestamp -> Text,
        read_status -> Text,
        msg_type -> Text,
        recipient -> Text,
    }
}

diesel::table! {
    action_log (id) {
        id -> BigInt,
        instance_id -> Text,
        action_id -> Text,
        action_type -> Text,
        action_input -> Text,
        action_output -> Nullable<Text>,
        status -> Text,
        distill_text -> Nullable<Text>,
        created_at -> Text,
    }
}

diesel::table! {
    memory_cursor (instance_id) {
        instance_id -> Text,
        current_cursor -> BigInt,
        updated_at -> Text,
    }
}

diesel::table! {
    knowledge_store (instance_id) {
        instance_id -> Text,
        content -> Text,
        updated_at -> Text,
    }
}

diesel::table! {
    history_store (instance_id) {
        instance_id -> Text,
        content -> Text,
        updated_at -> Text,
    }
}

diesel::table! {
    session_blocks (id) {
        id -> BigInt,
        instance_id -> Text,
        block_name -> Text,
        first_msg -> Text,
        last_msg -> Text,
        summary -> Text,
        created_at -> Text,
    }
}

// ---------------------------------------------------------------------------
// Models — messages
// ---------------------------------------------------------------------------

/// A complete message record (all columns, for SELECT queries).
#[derive(Debug, Clone, Queryable, Selectable)]
#[diesel(table_name = messages)]
pub struct MessageRow {
    pub id: i64,
    pub sender: String,
    pub role: String,
    pub content: String,
    pub timestamp: String,
    pub read_status: String,
    pub msg_type: String,
    pub recipient: String,
}

/// For inserting a new message (id is auto-generated by SQLite).
#[derive(Debug, Insertable)]
#[diesel(table_name = messages)]
pub struct NewMessage<'a> {
    pub sender: &'a str,
    pub role: &'a str,
    pub content: &'a str,
    pub timestamp: &'a str,
    pub read_status: &'a str,
    pub msg_type: &'a str,
    pub recipient: &'a str,
}

// ---------------------------------------------------------------------------
// Models — action_log
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Queryable, Selectable)]
#[diesel(table_name = action_log)]
pub struct ActionLogRow {
    pub id: i64,
    pub instance_id: String,
    pub action_id: String,
    pub action_type: String,
    pub action_input: String,
    pub action_output: Option<String>,
    pub status: String,
    pub distill_text: Option<String>,
    pub created_at: String,
}

#[derive(Debug, Insertable)]
#[diesel(table_name = action_log)]
pub struct NewActionLog<'a> {
    pub instance_id: &'a str,
    pub action_id: &'a str,
    pub action_type: &'a str,
    pub action_input: &'a str,
    pub action_output: Option<&'a str>,
    pub status: &'a str,
    pub distill_text: Option<&'a str>,
    pub created_at: &'a str,
}

// ---------------------------------------------------------------------------
// Models — memory_cursor
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Queryable, Selectable, Insertable)]
#[diesel(table_name = memory_cursor)]
pub struct MemoryCursorRow {
    pub instance_id: String,
    pub current_cursor: i64,
    pub updated_at: String,
}

// ---------------------------------------------------------------------------
// Models — knowledge_store
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Queryable, Selectable, Insertable)]
#[diesel(table_name = knowledge_store)]
pub struct KnowledgeRow {
    pub instance_id: String,
    pub content: String,
    pub updated_at: String,
}

// ---------------------------------------------------------------------------
// Models — history_store
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Queryable, Selectable, Insertable)]
#[diesel(table_name = history_store)]
pub struct HistoryRow {
    pub instance_id: String,
    pub content: String,
    pub updated_at: String,
}

// ---------------------------------------------------------------------------
// Models — session_blocks
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Queryable, Selectable)]
#[diesel(table_name = session_blocks)]
pub struct SessionBlockRow {
    pub id: i64,
    pub instance_id: String,
    pub block_name: String,
    pub first_msg: String,
    pub last_msg: String,
    pub summary: String,
    pub created_at: String,
}

#[derive(Debug, Insertable)]
#[diesel(table_name = session_blocks)]
pub struct NewSessionBlock<'a> {
    pub instance_id: &'a str,
    pub block_name: &'a str,
    pub first_msg: &'a str,
    pub last_msg: &'a str,
    pub summary: &'a str,
    pub created_at: &'a str,
}

// ---------------------------------------------------------------------------
// Constants — role/status/type values
// ---------------------------------------------------------------------------

pub const ROLE_USER: &str = "user";
pub const ROLE_AGENT: &str = "agent";
pub const ROLE_SYSTEM: &str = "system";
pub const STATUS_READ: &str = "read";
pub const STATUS_UNREAD: &str = "unread";
pub const TYPE_CHAT: &str = "chat";

// Action log status constants
pub const ACTION_STATUS_EXECUTING: &str = "executing";
pub const ACTION_STATUS_DONE: &str = "done";
pub const ACTION_STATUS_DISTILLED: &str = "distilled";

// ---------------------------------------------------------------------------
// Schema migration SQL (raw SQL, Diesel doesn't auto-migrate)
// ---------------------------------------------------------------------------

pub const CREATE_MESSAGES_TABLE: &str =
    "CREATE TABLE IF NOT EXISTS messages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        sender TEXT NOT NULL DEFAULT '',
        role TEXT NOT NULL DEFAULT '',
        content TEXT NOT NULL DEFAULT '',
        timestamp TEXT NOT NULL DEFAULT '',
        read_status TEXT NOT NULL DEFAULT '',
        msg_type TEXT NOT NULL DEFAULT '',
        recipient TEXT NOT NULL DEFAULT ''
    )";

pub const CREATE_ACTION_LOG_TABLE: &str =
    "CREATE TABLE IF NOT EXISTS action_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        instance_id TEXT NOT NULL,
        action_id TEXT NOT NULL,
        action_type TEXT NOT NULL,
        action_input TEXT NOT NULL,
        action_output TEXT,
        status TEXT NOT NULL DEFAULT 'executing',
        distill_text TEXT,
        created_at TEXT NOT NULL
    )";

pub const CREATE_ACTION_LOG_IDX_INSTANCE: &str =
    "CREATE INDEX IF NOT EXISTS idx_action_log_instance ON action_log(instance_id)";

pub const CREATE_ACTION_LOG_IDX_ACTION_ID: &str =
    "CREATE INDEX IF NOT EXISTS idx_action_log_action_id ON action_log(action_id)";

pub const CREATE_ACTION_LOG_IDX_TYPE: &str =
    "CREATE INDEX IF NOT EXISTS idx_action_log_type ON action_log(instance_id, action_type)";

pub const CREATE_MEMORY_CURSOR_TABLE: &str =
    "CREATE TABLE IF NOT EXISTS memory_cursor (
        instance_id TEXT PRIMARY KEY,
        current_cursor INTEGER NOT NULL DEFAULT 0,
        updated_at TEXT NOT NULL
    )";

pub const CREATE_KNOWLEDGE_STORE_TABLE: &str =
    "CREATE TABLE IF NOT EXISTS knowledge_store (
        instance_id TEXT PRIMARY KEY,
        content TEXT NOT NULL DEFAULT '',
        updated_at TEXT NOT NULL
    )";

pub const CREATE_HISTORY_STORE_TABLE: &str =
    "CREATE TABLE IF NOT EXISTS history_store (
        instance_id TEXT PRIMARY KEY,
        content TEXT NOT NULL DEFAULT '',
        updated_at TEXT NOT NULL
    )";

pub const CREATE_SESSION_BLOCKS_TABLE: &str =
    "CREATE TABLE IF NOT EXISTS session_blocks (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        instance_id TEXT NOT NULL,
        block_name TEXT NOT NULL,
        first_msg TEXT NOT NULL,
        last_msg TEXT NOT NULL,
        summary TEXT NOT NULL,
        created_at TEXT NOT NULL
    )";

pub const CREATE_SESSION_BLOCKS_INDEX: &str =
    "CREATE INDEX IF NOT EXISTS idx_session_blocks_instance ON session_blocks(instance_id)";

pub const CHECK_RECIPIENT_COLUMN: &str = "SELECT recipient FROM messages LIMIT 0";

pub const SELECT_LAST_INSERT_ROWID: &str = "SELECT last_insert_rowid()";

pub const ADD_RECIPIENT_COLUMN: &str =
    "ALTER TABLE messages ADD COLUMN recipient TEXT NOT NULL DEFAULT ''";