//! Tunnel — RPC over bidirectional transport (e.g. WebSocket).
//!
//! Provides typed remote procedure calls over any bidirectional message transport.
//! Business code defines pure traits, `#[tunnel_service]` macro generates proxy and dispatcher.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

// ─── Message Protocol ───

/// Request message.
#[derive(Debug, Serialize, Deserialize)]
struct RequestMessage {
    id: String,
    method: String,
    params: serde_json::Value,
}

/// Response message.
#[derive(Debug, Serialize, Deserialize)]
struct ResponseMessage {
    id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    result: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    error: Option<String>,
}

/// Parsed message — either request or response.
enum ParsedMessage {
    Request { id: String, method: String, params: serde_json::Value },
    Response { id: String, result: Result<serde_json::Value, String> },
}

fn parse_message(text: &str) -> Result<ParsedMessage, String> {
    let v: serde_json::Value = serde_json::from_str(text)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    if v.get("method").is_some() {
        let req: RequestMessage = serde_json::from_value(v)
            .map_err(|e| format!("request parse error: {}", e))?;
        Ok(ParsedMessage::Request { id: req.id, method: req.method, params: req.params })
    } else {
        let resp: ResponseMessage = serde_json::from_value(v)
            .map_err(|e| format!("response parse error: {}", e))?;
        let result = if let Some(err) = resp.error {
            Err(err)
        } else {
            Ok(resp.result.unwrap_or(serde_json::Value::Null))
        };
        Ok(ParsedMessage::Response { id: resp.id, result })
    }
}

fn make_request(id: &str, method: &str, params: serde_json::Value) -> String {
    serde_json::to_string(&RequestMessage {
        id: id.to_string(),
        method: method.to_string(),
        params,
    }).unwrap()
}

fn make_response_ok(id: &str, result: serde_json::Value) -> String {
    serde_json::to_string(&ResponseMessage {
        id: id.to_string(),
        result: Some(result),
        error: None,
    }).unwrap()
}

fn make_response_err(id: &str, error: String) -> String {
    serde_json::to_string(&ResponseMessage {
        id: id.to_string(),
        result: None,
        error: Some(error),
    }).unwrap()
}

// ─── Transport Trait ───

/// Abstraction over bidirectional message transport (WebSocket, channel, etc.).
pub trait Transport: Send {
    /// Send a text message.
    fn send(&mut self, text: &str) -> Result<(), String>;
    /// Receive next text message. Blocks until available. Returns None on close.
    fn recv(&mut self) -> Result<Option<String>, String>;
}

// ─── Dispatch Trait ───

/// Server-side method dispatcher. Generated by `#[tunnel_service]` macro.
pub trait Dispatch: Send + Sync {
    /// Dispatch a method call. Returns serialized result or error string.
    /// Returns Err("unknown method: ...") if method is not handled by this dispatcher.
    fn dispatch(&self, method: &str, params: serde_json::Value) -> Result<serde_json::Value, String>;
}

// ─── Tunnel Endpoint ───

type PendingMap = HashMap<String, std::sync::mpsc::SyncSender<Result<serde_json::Value, String>>>;

/// A bidirectional RPC endpoint over a Transport.
///
/// - Registers dispatchers for incoming requests
/// - Provides `call()` for outgoing requests (blocks until response)
/// - Runs a reader thread that routes incoming messages
pub struct TunnelEndpoint {
    writer: Arc<Mutex<Box<dyn Transport>>>,
    pending: Arc<Mutex<PendingMap>>,
    timeout: Duration,
}

impl TunnelEndpoint {
    /// Create a new endpoint with separate read/write transports.
    ///
    /// - `reader`: transport for receiving (moved to reader thread)
    /// - `writer`: transport for sending (shared between proxy and reader thread)
    /// - `dispatchers`: service dispatchers for incoming requests
    /// - `timeout`: request timeout duration
    pub fn new(
        reader: Box<dyn Transport>,
        writer: Box<dyn Transport>,
        dispatchers: Vec<Box<dyn Dispatch>>,
        timeout: Duration,
    ) -> Arc<Self> {
        let writer = Arc::new(Mutex::new(writer));
        let pending: Arc<Mutex<PendingMap>> = Arc::new(Mutex::new(HashMap::new()));
        let dispatchers = Arc::new(dispatchers);

        let endpoint = Arc::new(Self {
            writer: writer.clone(),
            pending: pending.clone(),
            timeout,
        });

        // Spawn reader thread
        let reader_writer = writer;
        let reader_pending = pending;
        let reader_dispatchers = dispatchers;
        std::thread::spawn(move || {
            reader_loop(reader, reader_writer, reader_pending, reader_dispatchers);
        });

        endpoint
    }

    /// Make a remote procedure call. Blocks until response or timeout.
    pub fn call(&self, method: &str, params: serde_json::Value) -> Result<serde_json::Value, String> {
        let id = generate_id();
        let text = make_request(&id, method, params);

        // Register pending request
        let (tx, rx) = std::sync::mpsc::sync_channel(1);
        {
            self.pending.lock().unwrap().insert(id.clone(), tx);
        }

        // Send request
        {
            let mut w = self.writer.lock().unwrap();
            w.send(&text).map_err(|e| {
                self.pending.lock().unwrap().remove(&id);
                e
            })?;
        }

        // Wait for response
        match rx.recv_timeout(self.timeout) {
            Ok(result) => result,
            Err(std::sync::mpsc::RecvTimeoutError::Timeout) => {
                self.pending.lock().unwrap().remove(&id);
                Err(format!("[TUNNEL] call '{}' timed out after {:?}", method, self.timeout))
            }
            Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                self.pending.lock().unwrap().remove(&id);
                Err(format!("[TUNNEL] call '{}': channel disconnected", method))
            }
        }
    }
}

fn reader_loop(
    mut reader: Box<dyn Transport>,
    writer: Arc<Mutex<Box<dyn Transport>>>,
    pending: Arc<Mutex<PendingMap>>,
    dispatchers: Arc<Vec<Box<dyn Dispatch>>>,
) {
    loop {
        let msg_text = match reader.recv() {
            Ok(Some(text)) => text,
            Ok(None) => break,
            Err(e) => {
                eprintln!("[TUNNEL] Reader error: {}", e);
                break;
            }
        };

        match parse_message(&msg_text) {
            Ok(ParsedMessage::Request { id, method, params }) => {
                let result = dispatch_request(&method, params, &dispatchers);
                let response_text = match result {
                    Ok(value) => make_response_ok(&id, value),
                    Err(error) => make_response_err(&id, error),
                };
                let mut w = writer.lock().unwrap();
                if let Err(e) = w.send(&response_text) {
                    eprintln!("[TUNNEL] Failed to send response: {}", e);
                }
            }
            Ok(ParsedMessage::Response { id, result }) => {
                let sender = pending.lock().unwrap().remove(&id);
                if let Some(tx) = sender {
                    let _ = tx.send(result);
                }
            }
            Err(e) => {
                eprintln!("[TUNNEL] Failed to parse message: {} — raw: {}", e, &msg_text[..200.min(msg_text.len())]);
            }
        }
    }
}

fn dispatch_request(
    method: &str,
    params: serde_json::Value,
    dispatchers: &[Box<dyn Dispatch>],
) -> Result<serde_json::Value, String> {
    for dispatcher in dispatchers {
        match dispatcher.dispatch(method, params.clone()) {
            Err(ref e) if e.starts_with("unknown method:") => continue,
            other => return other,
        }
    }
    Err(format!("unknown method: {}", method))
}

fn generate_id() -> String {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    format!("{:06x}", nanos % 0x1000000)
}

// ─── Channel Transport (for testing) ───

/// Writer half of a channel transport.
pub struct ChannelWriter {
    tx: std::sync::mpsc::Sender<String>,
}

/// Reader half of a channel transport.
pub struct ChannelReader {
    rx: std::sync::mpsc::Receiver<String>,
}

/// Create two pairs of (reader, writer) for bidirectional channel communication.
///
/// Returns ((reader_a, writer_a), (reader_b, writer_b)) where:
/// - writer_a sends to reader_b
/// - writer_b sends to reader_a
pub fn channel_transport_pair() -> ((ChannelReader, ChannelWriter), (ChannelReader, ChannelWriter)) {
    let (tx1, rx1) = std::sync::mpsc::channel();
    let (tx2, rx2) = std::sync::mpsc::channel();
    (
        (ChannelReader { rx: rx2 }, ChannelWriter { tx: tx1 }),
        (ChannelReader { rx: rx1 }, ChannelWriter { tx: tx2 }),
    )
}

impl Transport for ChannelWriter {
    fn send(&mut self, text: &str) -> Result<(), String> {
        self.tx.send(text.to_string()).map_err(|e| format!("channel send error: {}", e))
    }

    fn recv(&mut self) -> Result<Option<String>, String> {
        Err("ChannelWriter does not support recv".to_string())
    }
}

impl Transport for ChannelReader {
    fn send(&mut self, _text: &str) -> Result<(), String> {
        Err("ChannelReader does not support send".to_string())
    }

    fn recv(&mut self) -> Result<Option<String>, String> {
        match self.rx.recv() {
            Ok(text) => Ok(Some(text)),
            Err(_) => Ok(None),
        }
    }
}