//! Tunnel RPC framework - async implementation
//!
//! Provides bidirectional RPC over any async channel pair.
//! Used with `#[tunnel_service]` proc macro to generate Proxy and Dispatcher.

use serde_json::Value;
use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tokio::sync::{mpsc, oneshot};

// ── Message protocol ──────────────────────────────────────────

pub struct RequestMessage {
    pub id: String,
    pub method: String,
    pub params: Value,
}

pub struct ResponseMessage {
    pub id: String,
    pub result: Result<Value, String>,
}

pub enum ParsedMessage {
    Request(RequestMessage),
    Response(ResponseMessage),
}

pub fn make_request(msg: &RequestMessage) -> String {
    serde_json::to_string(&serde_json::json!({
        "type": "request",
        "id": msg.id,
        "method": msg.method,
        "params": msg.params,
    })).unwrap()
}

pub fn make_response(msg: &ResponseMessage) -> String {
    let value = match &msg.result {
        Ok(v) => serde_json::json!({"type": "response", "id": msg.id, "result": v}),
        Err(e) => serde_json::json!({"type": "response", "id": msg.id, "error": e}),
    };
    serde_json::to_string(&value).unwrap()
}

pub fn parse_message(text: &str) -> Option<ParsedMessage> {
    let v: Value = serde_json::from_str(text).ok()?;
    let msg_type = v.get("type")?.as_str()?;
    match msg_type {
        "request" => {
            let id = v.get("id")?.as_str()?.to_string();
            let method = v.get("method")?.as_str()?.to_string();
            let params = v.get("params")?.clone();
            Some(ParsedMessage::Request(RequestMessage { id, method, params }))
        }
        "response" => {
            let id = v.get("id")?.as_str()?.to_string();
            if let Some(error) = v.get("error") {
                let error_str = error.as_str().unwrap_or("unknown error").to_string();
                Some(ParsedMessage::Response(ResponseMessage {
                    id,
                    result: Err(error_str),
                }))
            } else {
                let result = v.get("result")?.clone();
                Some(ParsedMessage::Response(ResponseMessage {
                    id,
                    result: Ok(result),
                }))
            }
        }
        _ => None,
    }
}

// ── Dispatch trait ─────────────────────────────────────────────

/// Trait for dispatching incoming RPC requests to local handlers.
/// Implementations are generated by `#[tunnel_service]` macro.
#[async_trait::async_trait]
pub trait Dispatch: Send + Sync {
    /// Returns the service prefix this dispatcher handles (e.g., "MyService")
    fn service_name(&self) -> &str;

    /// Dispatch a method call. method is the full "ServiceName.method_name" string.
    async fn dispatch(&self, method: &str, params: Value) -> Result<Value, String>;
}

// ── TunnelEndpoint ─────────────────────────────────────────────

type PendingMap = HashMap<String, oneshot::Sender<Result<Value, String>>>;

/// Async bidirectional RPC endpoint over channel pairs.
///
/// Create with `TunnelEndpoint::new()`, which spawns an async reader task.
/// Use `call()` to make RPC requests to the remote side.
pub struct TunnelEndpoint {
    outgoing_tx: mpsc::UnboundedSender<String>,
    pending: Arc<Mutex<PendingMap>>,
    timeout: Duration,
}

impl TunnelEndpoint {
    /// Create a new TunnelEndpoint and spawn the reader loop.
    ///
    /// - `incoming_rx`: receives messages from the remote side
    /// - `outgoing_tx`: sends messages to the remote side
    /// - `dispatchers`: local RPC handlers for incoming requests
    /// - `timeout`: how long `call()` waits for a response
    pub fn new(
        incoming_rx: mpsc::UnboundedReceiver<String>,
        outgoing_tx: mpsc::UnboundedSender<String>,
        dispatchers: Vec<Box<dyn Dispatch>>,
        timeout: Duration,
    ) -> Arc<Self> {
        let pending: Arc<Mutex<PendingMap>> = Arc::new(Mutex::new(HashMap::new()));

        let endpoint = Arc::new(Self {
            outgoing_tx: outgoing_tx.clone(),
            pending: pending.clone(),
            timeout,
        });

        // Spawn async reader loop
        tokio::spawn(reader_loop(incoming_rx, outgoing_tx, dispatchers, pending));

        endpoint
    }

    /// Make an RPC call to the remote side.
    ///
    /// Sends a request and waits for the response (with timeout).
    pub async fn call(
        &self,
        method: &str,
        params: Value,
    ) -> Result<Value, String> {
        let id = generate_id();

        let (tx, rx) = oneshot::channel();

        // Register pending request
        {
            let mut map = self.pending.lock().unwrap();
            map.insert(id.clone(), tx);
        }

        // Send request
        let msg = make_request(&RequestMessage {
            id: id.clone(),
            method: method.to_string(),
            params,
        });

        if self.outgoing_tx.send(msg).is_err() {
            // Clean up pending
            let mut map = self.pending.lock().unwrap();
            map.remove(&id);
            return Err("tunnel disconnected".to_string());
        }

        // Wait for response with timeout
        match tokio::time::timeout(self.timeout, rx).await {
            Ok(Ok(result)) => result,
            Ok(Err(_)) => {
                // oneshot sender dropped — endpoint shutting down
                Err("tunnel endpoint closed".to_string())
            }
            Err(_) => {
                // Timeout — clean up pending
                let mut map = self.pending.lock().unwrap();
                map.remove(&id);
                Err(format!("tunnel call timeout: {}", method))
            }
        }
    }
}

/// Async reader loop — processes incoming messages from the remote side.
async fn reader_loop(
    mut incoming_rx: mpsc::UnboundedReceiver<String>,
    outgoing_tx: mpsc::UnboundedSender<String>,
    dispatchers: Vec<Box<dyn Dispatch>>,
    pending: Arc<Mutex<PendingMap>>,
) {
    while let Some(text) = incoming_rx.recv().await {
        let parsed = match parse_message(&text) {
            Some(p) => p,
            None => continue,
        };

        match parsed {
            ParsedMessage::Request(req) => {
                // Find matching dispatcher
                let mut result = Err(format!("no handler for method: {}", req.method));
                for dispatcher in &dispatchers {
                    if req.method.starts_with(dispatcher.service_name()) {
                        result = dispatcher.dispatch(&req.method, req.params.clone()).await;
                        break;
                    }
                }

                // Send response
                let response = make_response(&ResponseMessage {
                    id: req.id,
                    result,
                });
                let _ = outgoing_tx.send(response);
            }
            ParsedMessage::Response(resp) => {
                // Find and notify pending caller
                let sender = {
                    let mut map = pending.lock().unwrap();
                    map.remove(&resp.id)
                };
                if let Some(sender) = sender {
                    let _ = sender.send(resp.result);
                }
            }
        }
    }

    // Channel closed — clean up all pending requests
    let mut map = pending.lock().unwrap();
    for (_, sender) in map.drain() {
        let _ = sender.send(Err("tunnel disconnected".to_string()));
    }
}

// ── Utilities ──────────────────────────────────────────────────

fn generate_id() -> String {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("rpc_{}", n)
}

/// Create a pair of connected channel pairs for testing.
///
/// Returns ((incoming_rx_a, outgoing_tx_a), (incoming_rx_b, outgoing_tx_b))
/// where A's outgoing connects to B's incoming and vice versa.
pub fn channel_pair() -> (
    (mpsc::UnboundedReceiver<String>, mpsc::UnboundedSender<String>),
    (mpsc::UnboundedReceiver<String>, mpsc::UnboundedSender<String>),
) {
    let (a_to_b_tx, a_to_b_rx) = mpsc::unbounded_channel();
    let (b_to_a_tx, b_to_a_rx) = mpsc::unbounded_channel();
    // A's outgoing → B's incoming, B's outgoing → A's incoming
    ((b_to_a_rx, a_to_b_tx), (a_to_b_rx, b_to_a_tx))
}